# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.0

jobs:
  "ruby-2.3":
    docker:
      - image: circleci/ruby:2.3
    working_directory: ~/acts_as_mentionable
    steps:
      - checkout
      - run: bundle install --path vendor/bundle
      - run:
          name: RSpec
          command: bundle exec rspec

  "ruby-2.4":
    docker:
      - image: circleci/ruby:2.4
    working_directory: ~/acts_as_mentionable
    steps:
      - checkout
      - run: bundle install --path vendor/bundle
      - run:
          name: Lint
          command: |
            bundle exec rubocop
      - run:
          name: RSpec
          command: bundle exec rspec

  "ruby-2.5":
    docker:
      - image: circleci/ruby:2.5
    working_directory: ~/acts_as_mentionable
    steps:
      - checkout
      - run: bundle install --path vendor/bundle
      - run:
          name: Lint
          command: |
            bundle exec rubocop
      - run:
          name: RSpec
          command: bundle exec rspec

workflows:
  version: 2
  build:
    jobs:
      - "ruby-2.3"
      - "ruby-2.4"
      - "ruby-2.5"
